# Use a base image with necessary dependencies
FROM python:3.11-slim-buster

# Set the working directory
WORKDIR /code

# Install system dependencies
RUN apt-get update && apt-get install -y libselinux-devel

# Copy requirements.txt and install dependencies
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Copy the project code
COPY . .

# Expose the port
EXPOSE 8000

# Command to run the app
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
